### ISSUE TITLE
【测试】能否用于 SSR - next.js 和 nuxt.js

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/we-2021#119]
## 问题描述

如题。测试 v5 能否用于 SSR （next.js 和 nuxt.js）

## wangEditor 版本

v5

**Comment by shi-lai-mu** [comment]
【问题记录】NextJS URL校验报错如下
![image](https://user-images.githubusercontent.com/45140991/129471369-5b5f3399-6925-49ab-91ff-a6a630cd71fd.png)

**Comment by shi-lai-mu** [comment]
【问题记录】
> NustJs在使用@wangeditor/editor-for-vue时mjs报错如下
Can't import the named export 'createEditor' from non EcmaScript module (only default export is available)
![image](https://user-images.githubusercontent.com/45140991/129471398-445758ce-dce1-4127-9f58-bfcb1e043e90.png)
解决方法 nuxt.config build 编译时增加如下rules
```javascript
config.module.rules.push({
        test: /\.mjs$/i,
        type: "javascript/auto"
})
// 注意：不能添加include node_modules
```

**Comment by shi-lai-mu** [comment]
【问题记录】
> NuxtJs在使用@wangeditor/editor-for-vue时Vue报如下 编译、DOM不匹配错误

- [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

- [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

![image](https://user-images.githubusercontent.com/45140991/129471545-91eb39c4-4781-4925-a457-b3bb4ac99946.png)

## 解决方法 nuxt.config build 编译时增加如下alias
```javascript
config.resolve.alias['vue$'] = 'vue/dist/vue.esm.js'
```

**Comment by shi-lai-mu** [comment]
【NuxtJS 问题记录】兼容nodejs定义window时报错如下
![image](https://user-images.githubusercontent.com/45140991/129471997-51244cb4-a42f-49cf-bbb9-348514ff1af6.png)
已修复 #134

**Comment by shi-lai-mu** [comment]
Demo如下
- [NextJS](https://github.com/shi-lai-mu/wangEditor/tree/demo/wangeditor-v5-NextJS-ts)
- [NuxtJS](https://github.com/shi-lai-mu/wangEditor/tree/demo/wangeditor-v5-NuxtJS-ts)
